apiVersion: apps/v1
kind: Service

metadata:
  name: commandnp-service

spec:
  type: NodePort
  selector:
    app: commandservice
  ports:
    - name: commandservice
      protocol: TCP
      port: 80
      targetPort: 80